version: '3'

services:
  ubuntu:
    container_name: entorno_bash
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
    volumes:
      - ./ejercicios_bash:/home/${USER_NAME}
    stdin_open: true
    tty: true
    command: /bin/bash